### ISSUE TITLE
Search all courses within TimeTable Page

### ISSUE THREAD

**Issue by omgkaustav** [DevCom-IITB/ResoBin#50]
**Is your feature request related to a problem? Please describe.**
Currently, the only way to add a new course to your timetable is by going to the course search page, searching for the course and adding it to your timetable, which is somewhat cumbersome.

**Describe the solution you'd like**
The ability to search courses and add them in the timetable slot should be present within the TimeTable Page itself.

**Comment by vk0812** [comment]
Done
