### ISSUE TITLE
Valentine's Day easter eggs

### ISSUE THREAD

**Issue by ayushk26** [DevCom-IITB/ResoBin#61]
- [ ] Pink theme for Valentines day
- [x] Release timetable sharing with a cheezy pitch

**Comment by vedk** [comment]
- [ ] Two to three new courses will be added, e.g. Salsa Night 101 (SALSA 101)
- [ ] A portal where people can talk about their plans for Valentine's Day.
- [ ] Salsa 101 Course will have a list of locations in the campus where people can make out
- [ ] Find the number of people who are using ResoBin on Valentine's day, esp. on 13 Feb 11:59 pm.
