### ISSUE TITLE
Half sem courses shows slot clashes 

### ISSUE THREAD

**Issue by AdithyaKrishnaK** [DevCom-IITB/ResoBin#84]
Course slot clashing warning don't differentiate between half sem and full sem courses. This is a problem while making freshie timetables because they have a lot of half sem courses. A solution to this could be to relax the slot clash check if there are two half sem courses in the same slot.

<img width="799" alt="image" src="https://user-images.githubusercontent.com/24326156/224240388-5c7e4002-392e-4a7a-bd82-5f10590dd09c.png">

**Comment by ayushk26** [comment]
By relaxing the slot clashes, both courses have to appear on same place in the timetable. Have you planned any UI/layout to show such courses? @AdithyaKrishnaK
