### ISSUE TITLE
Total Number of credits in the time table page

### ISSUE THREAD

**Issue by AdithyaKrishnaK** [DevCom-IITB/ResoBin#92]
**Problem**
The current implementation of the timetable page lacks information about the total number of credits associated with each course. This information is crucial for users to plan their semester effectively and understand the overall workload. This issue seeks to introduce a feature that displays the credits for each course on the timetable page.

**Objective**
The goal of this issue is to enhance the user experience by providing a clear display of the total number of credits associated with each course on the timetable page. This information is valuable for users in planning and managing their course load.

**Proposed Solution**
1. **Design**
   - Propose a design that incorporates the display of credits for each course on the timetable page.
   - Consider placement options of the credits such as on the course component or a dedicated section on the right-hand side.

2. **Code Implementation**
   - Once the design is finalized, proceed with the code implementation to dynamically fetch and display the credits for each course.
   - Ensure that the display is intuitive, informative, and does not clutter the overall layout.

**Expected Outcome**
- A well-thought-out design concept that effectively communicates the credits associated with each course.
- Code implementation that seamlessly integrates the credit display feature into the existing timetable functionality.

**Note to Developers**
Begin by presenting a sample design that incorporates the display of credits for each course. Once the design is approved, proceed with the implementation, ensuring the code aligns with best practices and enhances the overall usability of the timetable page. Collaborate with the community for feedback and support throughout this enhancement process.

**Comment by vk0812** [comment]
Solved PR #102
