### ISSUE TITLE
Timetable PNG on Mobile

### ISSUE THREAD

**Issue by vk0812** [DevCom-IITB/ResoBin#96]
**Problem**
Currently, the functionality for downloading the Timetable as a PNG on mobile devices is not yielding satisfactory results. The existing implementation relies on taking a screenshot of the timetable component, leading to suboptimal output.

**Objective**
The goal of this issue is to enhance the Timetable PNG download feature on mobile devices to produce better-quality results without resorting to the screenshot approach.

**Proposed Solution**
Avoid implementing any screenshot-based methods for downloading the Timetable as a PNG. Instead, explore alternative solutions that ensure a more accurate and visually appealing representation of the timetable on mobile devices.

**Expected Behavior**
- The Timetable PNG download feature should generate clear and images of the timetable.
- The solution should be optimized for mobile devices, considering various screen sizes and resolutions.

**Note to Developers**
Please refrain from implementing any screenshot-based methods for the Timetable PNG download. Feel free to explore alternative approaches that align with the objectives mentioned above. If you encounter any challenges or have questions, don't hesitate to seek assistance from the project community.

**Comment by sethigeet** [comment]
We can instead let them print the page as we can apply separate styles for printing and we can ensure that the print output is the same regardless of the screen size.

**Comment by vk0812** [comment]
Yes that is one way, but printing the page would print lots of unnecessary data which no one needs. People just want the timetable.

**Comment by sethigeet** [comment]
No that's not true. We can hide all the other elements that we do not want using css and only leave the timetable component visible.

**Comment by vk0812** [comment]
Yes but wouldnt this be too much pain, can we find some easy solution maybe using some other react libraries which help in doing the same

**Comment by AdithyaKrishnaK** [comment]
This issue could also be because of faulty implementation, see https://github.com/tsayen/dom-to-image/issues/107

**Comment by vk0812** [comment]
Solved PR #105
